---
on: [push, pull_request]
name: Integration tests

jobs:
  integration-tests:
    uses: coreruleset/crs-plugin-test-action/.github/workflows/integration.yaml@deb03b0ef2f24b3d2b5cbc5fc6f1b6d3792cc319 # main
